/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.NurseRole;

import Business.EcoSystem;
import Business.Encounter.Encounter;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabWorkRequest;
import Business.WorkQueue.NurseWorkRequest;
import Business.WorkQueue.WorkRequest;
import UserInterface.DoctorRole.CreatePaitentJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krunal Nisar
 */
public class NurseWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NurseWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount; 
    Organization organization;
    Enterprise enterprise;
    Network network;
   

    public NurseWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, EcoSystem system, Network network) {
           initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise=enterprise;
        this.userAccount = userAccount;
        this.network = network;
        NurseTable();
    }
        public void NurseTable()
        {
            
             DefaultTableModel model = (DefaultTableModel) NurseRequestTable.getModel();
        
        model.setRowCount(0);
        for(WorkRequest wr : organization.getWorkQueue().getWorkRequestList())
        {
            Object row [] = new Object[6];
            row[0]= wr;
            row[1]=wr.getPatient().getName();
            row[2]=wr.getEnocunter();
            row[3]=wr.getSender();
            row[4]=wr.getReceiver();
            String result = ((NurseWorkRequest)wr).getTestResult();
            row[5]=result==null ? "waiting" : result;
            model.addRow(row);
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProcessButton = new javax.swing.JButton();
        AssisgnButtoon = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        NurseRequestTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        ProcessButton.setText("Process Request ");
        ProcessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessButtonActionPerformed(evt);
            }
        });

        AssisgnButtoon.setText("Assign to me");
        AssisgnButtoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssisgnButtoonActionPerformed(evt);
            }
        });

        NurseRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Message", "patient", "Reason", "Sender", "Receiver", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(NurseRequestTable);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("           Nurse Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(AssisgnButtoon)
                        .addGap(18, 18, 18)
                        .addComponent(ProcessButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AssisgnButtoon, ProcessButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AssisgnButtoon)
                    .addComponent(ProcessButton))
                .addContainerGap(630, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AssisgnButtoon, ProcessButton});

    }// </editor-fold>//GEN-END:initComponents

    private void ProcessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessButtonActionPerformed
        // TODO add your handling code here:
        int selectRow = NurseRequestTable.getSelectedRow();
        if(selectRow < 0)
        {
            JOptionPane.showMessageDialog(null, "Kindly Select a row");
            return;
        }

        WorkRequest workRequest = (WorkRequest) NurseRequestTable.getValueAt(selectRow, 0);
        //Patient patient = workRequest.getPatient();
        Encounter encounter = workRequest.getEnocunter();
        //Assessment assessment = encounter.getAssessmentHistory().createAssessment();

        CollectVitalSignWorkArea cvsswa = new CollectVitalSignWorkArea(userProcessContainer,userAccount,encounter,enterprise,network,workRequest);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("CollectVitalSignWorkArea", cvsswa);
        layout.next(userProcessContainer);

    }//GEN-LAST:event_ProcessButtonActionPerformed

    private void AssisgnButtoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssisgnButtoonActionPerformed
        // TODO add your handling code here:
        int selectRow = NurseRequestTable.getSelectedRow();
        if(selectRow < 0)
        {
            JOptionPane.showMessageDialog(null, "Kindly Select a row");
            return;
        }

        WorkRequest workRequest = (WorkRequest) NurseRequestTable.getValueAt(selectRow, 0);
        workRequest.setReceiver(userAccount);
        workRequest.setStatus("pending");
        NurseTable();

    }//GEN-LAST:event_AssisgnButtoonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssisgnButtoon;
    private javax.swing.JTable NurseRequestTable;
    private javax.swing.JButton ProcessButton;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
