/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.DoctorRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.FDAEnterprise;
import Business.Network.City;
import Business.Network.Network;
import Business.Network.State;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DoctortoFDAWorkRequest;
import Business.WorkQueue.PatienttoDoctorWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krunal Nisar
 */
public class PatientComplainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientComplain
     */
        JPanel userProcessContainer;
        UserAccount userAccount; 
        Organization organization;
        Enterprise enterprise;
        Network network;
    public PatientComplainJPanel(JPanel userProcessContainer, UserAccount userAccount,  Organization organization, Enterprise enterprise,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise= enterprise;
        this.network=network;
        populateComplain();
    }
    
    public void populateComplain()
    {
        DefaultTableModel model = (DefaultTableModel) ReportTable.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest wr : userAccount.getWorkQueue().getWorkRequestList())
            
            {
               if(wr instanceof PatienttoDoctorWorkRequest)
                {
                Object[] row = new Object[9];
                row[0]=wr.getEnocunter().getStartDate();
                row[1]=wr.getEnocunter().getEnterprise();
                row[2]=wr.getSender();
                row[3]=wr;
                row[4]=((PatienttoDoctorWorkRequest)wr).getPrescription();
                row[5]=wr.getStatus();
           
                model.addRow(row);
                }
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ReportTable = new javax.swing.JTable();
        ReportFDA = new javax.swing.JButton();
        FeedbackTF = new javax.swing.JButton();
        feedbackTF = new javax.swing.JTextField();
        fdaMessage = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Hospital", "Sender", "Reaction", "Medication", "Feedback"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ReportTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 102, 721, 99));

        ReportFDA.setText("Report FDA");
        ReportFDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportFDAActionPerformed(evt);
            }
        });
        add(ReportFDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 120, -1));

        FeedbackTF.setText("Feedback");
        FeedbackTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeedbackTFActionPerformed(evt);
            }
        });
        add(FeedbackTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 233, -1, -1));
        add(feedbackTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 234, 106, -1));
        add(fdaMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 89, 25));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("                    Patients Complain");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 44, 535, 40));

        jButton2.setText("<<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 293, 106, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ReportFDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportFDAActionPerformed
        // TODO add your handling code here:
          int selectedRow =  ReportTable.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null, "Kindly select a row");
            return;
        }
        
        Organization FDAOrg = null;
        PatienttoDoctorWorkRequest wr = (PatienttoDoctorWorkRequest) ReportTable.getValueAt(selectedRow, 3);
        DoctortoFDAWorkRequest request = new DoctortoFDAWorkRequest();
        request.setMessage(wr.getMessage());
        request.setPatient(wr.getPatient());
        request.setPrescription(wr.getPrescription());
       // request.getEnocunter().setSideEffects(wr.getEnocunter().getSideEffects());
        request.setSender(userAccount);
        request.setStatus("ALERT");
        
        for(State state : network.getStateList())
        {
                for(City city : state.getCityList())
                {
                    for(Enterprise e : city.getEnterpriseDir().getEnterpriseList())
                    {
                        if (e instanceof FDAEnterprise)
                                {
                                    for(Organization o : e.getOrganizationDir().getOrganizationList())
                                    {
                                        FDAOrg = o;
                                        break;
                                        
                                    }
                                }
                    }
                }
        }
        FDAOrg.getWorkQueue().getWorkRequestList().add(request);
        
        populateComplain();
        
    }//GEN-LAST:event_ReportFDAActionPerformed

    private void FeedbackTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeedbackTFActionPerformed
        // TODO add your handling code here:
         int selectedRow =  ReportTable.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null, "Kindly select a row");
            return;
        }
        
        WorkRequest wr = (WorkRequest) ReportTable.getValueAt(selectedRow, 3);
        wr.setStatus(feedbackTF.getText());
        wr.setReceiver(userAccount);
       // wr.setMessage(feedbackTF.getText());
        populateComplain();
    }//GEN-LAST:event_FeedbackTFActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FeedbackTF;
    private javax.swing.JButton ReportFDA;
    private javax.swing.JTable ReportTable;
    private javax.swing.JTextField fdaMessage;
    private javax.swing.JTextField feedbackTF;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
