/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.PharmacyRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmacyEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FDAtoManufactureWorkRequest;
import Business.WorkQueue.PharmaceuticaltoPharmacyWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krunal Nisar
 */
public class ManufactureJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManufactureJPanel
     */
    JPanel userProcessContainer;
    PharmacyEnterprise enterprise;
    Network network;
    Organization organization;
    UserAccount userAccount;
    public ManufactureJPanel(JPanel userProcessContainer,Enterprise enterprise,Network network,Organization organization, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise=(PharmacyEnterprise) enterprise;
        this.network=network;
        this.organization=organization;
         this.userAccount = userAccount;
         RequestManufactureTable();
    }

    public void RequestManufactureTable()
    {
        DefaultTableModel model = (DefaultTableModel) MedicineTable.getModel();
        
        model.setRowCount(0);
        for(WorkRequest wr : organization.getWorkQueue().getWorkRequestList())
        {
            if(wr instanceof PharmaceuticaltoPharmacyWorkRequest)
            {
            Object row [] = new Object[6];
            row[0]= ((PharmaceuticaltoPharmacyWorkRequest)wr).getMedicine();
            row[1]=((PharmaceuticaltoPharmacyWorkRequest)wr).getMedicine().getSideEffects();
            row[2]=wr.getSender();
            row[3]=wr.getReceiver();
            row[4]=wr;
            row[5]=wr.getStatus();
            model.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        MedicineTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        updateTF = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MedicineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Medicine", "Side Effects", "Sender", "Reciever", "Details", "Pharmacy Status"
            }
        ));
        jScrollPane2.setViewportView(MedicineTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 725, 137));

        jButton1.setText("Update Request");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 165, 39));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("      Manufacture Notices");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 308, 41));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 100, 39));
        add(updateTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 180, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         int selectRow = MedicineTable.getSelectedRow();
        if(selectRow < 0)
        {
            JOptionPane.showMessageDialog(null, "Kindly Select a row");
            return;
        }
        
        PharmaceuticaltoPharmacyWorkRequest workRequest = (PharmaceuticaltoPharmacyWorkRequest) MedicineTable.getValueAt(selectRow, 4);
        workRequest.setReceiver(userAccount);
        workRequest.setStatus("Product Callbacked");
        workRequest.setMessage(updateTF.getText());
        RequestManufactureTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MedicineTable;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField updateTF;
    // End of variables declaration//GEN-END:variables
}
