/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SystemAdminRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.City;
import Business.Network.Network;
import Business.Network.State;
import Business.Organization.Organization;
import Business.Role.ClinicAdminRole;
import Business.Role.FDARole;
import Business.Role.HospitalAdminRole;
import Business.Role.PharmaceuticalAdminRole;
import Business.Role.PharmacyAdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krunal Nisar
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseAdminJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    public ManageEnterpriseAdminJPanel(JPanel userProcessContainer , EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system =  system;
        populateTable();
        populateEnterpriseComboBox();
        //populateNetworkComboBox();
    }

    public void populateEnterpriseComboBox()
    {
        enterpriseJComboBox.removeAllItems();
        for(Network network : system.getNetworkList())
        {
        for(State state : network.getStateList())
        {
            for(City city:state.getCityList())
            {
        for(Enterprise enterprise : city.getEnterpriseDir().getEnterpriseList()) 
               {
                       enterpriseJComboBox.addItem(enterprise);
              }
    }
        }
        }
    }
//    
//    private void populateNetworkComboBox(){
//        networkJComboBox.removeAllItems();
//        
//        
//        for(Network network: system.getNetworkList()){
//            networkJComboBox.addItem(network);
//        }
//        
//    }
//    
//     private void populateStateComboBox(Network network){
//        networkJComboBox.removeAllItems();
//        
//        
//        for(State network: network.getStateList()){
//            networkJComboBox.addItem(network);
//        }
//        
//    }
//     
//      private void populateCityComboBox(){
//        networkJComboBox.removeAllItems();
//        
//        
//        for(Network network: system.getNetworkList()){
//            networkJComboBox.addItem(network);
//        }
//        
//    }
 
    
    public void populateTable()
    {
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        for(Network network: system.getNetworkList())
        {
            for(State state : network.getStateList())
            {
            for(City city : state.getCityList())
            {
             
                for(Enterprise enterprise : city.getEnterpriseDir().getEnterpriseList())
                
                {
                    for(UserAccount ua: enterprise.getUserAccountDir().getUserAccountList()){
                Object[] row=new Object[6];
                
                row[0]= enterprise.getName();
                row[1]= network.getName();
                row[2]=state.getName();
                row[3]=city.getName();
                row[4]= ua.getUsername();
                row[5]=enterprise.getEnterpriseType();
                
                model.addRow(row);
                }
            }
        }
        }
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseJComboBox = new javax.swing.JComboBox();
        UsernameTF = new javax.swing.JTextField();
        PasswordTF = new javax.swing.JTextField();
        NameTF = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        enterpriseJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseJComboBoxActionPerformed(evt);
            }
        });
        add(enterpriseJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 181, 81, 25));
        add(UsernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 224, 81, 25));
        add(PasswordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 267, 81, 25));
        add(NameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 310, 81, 25));

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        add(SubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 353, 81, -1));

        BackButton.setText("<< Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 353, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Enterprise Name", "Country", "State", "City", "Username", "Enterprise Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 696, 93));

        jLabel2.setText("Enterprise");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 181, 81, 25));

        jLabel3.setText("UserName");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 224, 81, 25));

        jLabel4.setText("Password");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 267, 81, 25));

        jLabel5.setText("Name");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 310, 81, 25));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("         Manage Enterprise Login ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 13, 357, 39));
    }// </editor-fold>//GEN-END:initComponents

    private void enterpriseJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterpriseJComboBoxActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        UserAccount ua=null;
        Enterprise enterprise=(Enterprise) enterpriseJComboBox.getSelectedItem();

        String userName= UsernameTF.getText();
        String passwd= PasswordTF.getText();
        String name= NameTF.getText();
        
      
 if (userName.equals("") || passwd.equals("") || name.equals("")) {
            JOptionPane.showMessageDialog(null, "Fields empty!!");
            return;
        }

        for (Network n : system.getNetworkList()) {
            for (State sn : n.getStateList()) {
                for (City cn : sn.getCityList()) {
                    for (Enterprise e : cn.getEnterpriseDir().getEnterpriseList()) {
                        for (UserAccount ua1 : e.getUserAccountDir().getUserAccountList()) {
                            if (ua1.getUsername().equals(userName)) {
                                JOptionPane.showMessageDialog(null, "User already exists");
                                return;

                            } else {
                                for (Organization o : e.getOrganizationDir().getOrganizationList()) {
                                    for (UserAccount ua2 : o.getUserAccountDir().getUserAccountList()) {
                                        if (ua2.getUsername().equals(userName)) {
                                            JOptionPane.showMessageDialog(null, "User already exists");
                                            return;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        Employee employee= enterprise.getEmployeeDir().addEmployee(name);
        if(enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Hospital))
                {
                    ua=enterprise.getUserAccountDir().createUserAccount(userName, passwd, employee, new HospitalAdminRole());
                }
        else if(enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Clinic))
        {
            ua=enterprise.getUserAccountDir().createUserAccount(userName, passwd, employee, new ClinicAdminRole());
        }
        
        else if(enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Pharmacy))
        {
            ua=enterprise.getUserAccountDir().createUserAccount(userName, passwd, employee, new PharmacyAdminRole());
        }
        else if(enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Pharmaceutical))
        {
            ua=enterprise.getUserAccountDir().createUserAccount(userName, passwd, employee, new PharmaceuticalAdminRole());
        }
         else if(enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.FDA))
        {
            ua=enterprise.getUserAccountDir().createUserAccount(userName, passwd, employee, new FDARole());
        }
         else
        {
            JOptionPane.showMessageDialog(null, "Wrong Option");
        }
            

        populateTable();
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField NameTF;
    private javax.swing.JTextField PasswordTF;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JTextField UsernameTF;
    private javax.swing.JComboBox enterpriseJComboBox;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
