/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.FDA;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.FDAEnterprise;
import Business.Medicine.Medicine;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FDAWorkRequest;
import Business.WorkQueue.NurseWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krunal Nisar
 */
public class ApproveRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ApproveRequest
     */
    FDAEnterprise enterprise;
    JPanel userProcessContainer;
    UserAccount userAccount;
    Organization organization;
            
    ApproveRequestJPanel(JPanel userProcessContainer,Enterprise enterprise,UserAccount userAccount,Organization organization) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.enterprise = (FDAEnterprise) enterprise;
        this.userAccount = userAccount;
        this.organization = organization;
        populateTable();
    }

     public void populateTable()
        {
            
        DefaultTableModel model = (DefaultTableModel) ApproveTable.getModel();
            System.out.println(organization);
        model.setRowCount(0);
        for(WorkRequest wr : organization.getWorkQueue().getWorkRequestList())
        {
            if(wr instanceof FDAWorkRequest)
            {
            System.out.println("check");
            Object row [] = new Object[5];
            row[0]= wr;
            row[1]=wr.getSender();
            row[2]=((FDAWorkRequest)wr).getMedicine();
            row[3]=wr.getReceiver();
            row[4]=wr.getStatus();
            model.addRow(row);
            }
        }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ApproveTable = new javax.swing.JTable();
        Approve = new javax.swing.JButton();
        Decline = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        ApproveTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Message", "Manufacturer", "Medicine", "Receiver", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ApproveTable);

        Approve.setText("Approve and Add");
        Approve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApproveActionPerformed(evt);
            }
        });

        Decline.setText("Decline");
        Decline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeclineActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("   Approve Drug License Request");

        jButton1.setText("View Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(backJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Approve)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Decline)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(278, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Approve)
                    .addComponent(Decline)
                    .addComponent(backJButton)
                    .addComponent(jButton1))
                .addContainerGap(485, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void ApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApproveActionPerformed
        // TODO add your handling code here:
        int selectRow = ApproveTable.getSelectedRow();
        if(selectRow < 0)
        {
            JOptionPane.showMessageDialog(null, "Kindly Select a row");
            return;
        }
        
        FDAWorkRequest workRequest = (FDAWorkRequest) ApproveTable.getValueAt(selectRow, 0);
        workRequest.setReceiver(userAccount);
        workRequest.setStatus("Approved");
        
        
        Medicine medicine = ((FDAWorkRequest)workRequest).getMedicine();
       // Employee e = userAccount.getEmployee();
       // enterprise.getMedicineDir().addMedicine(medicine);
        enterprise.getApprovedList().add(medicine);
        populateTable();
        
    }//GEN-LAST:event_ApproveActionPerformed

    private void DeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeclineActionPerformed
        // TODO add your handling code here:
        int selectRow = ApproveTable.getSelectedRow();
        if(selectRow < 0)
        {
            JOptionPane.showMessageDialog(null, "Kindly Select a row");
            return;
        }
        
        WorkRequest workRequest = (WorkRequest) ApproveTable.getValueAt(selectRow, 0);
        workRequest.setReceiver(userAccount);
        workRequest.setStatus("Declined");
        populateTable();
    }//GEN-LAST:event_DeclineActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         int selectRow = ApproveTable.getSelectedRow();
        if(selectRow < 0)
        {
            JOptionPane.showMessageDialog(null, "Kindly Select a row");
            return;
        }
        
        FDAWorkRequest workRequest = (FDAWorkRequest) ApproveTable.getValueAt(selectRow, 0);
        Medicine medicine = ((FDAWorkRequest)workRequest).getMedicine();
        
        ViewReportJPanel vrjp = new ViewReportJPanel( userProcessContainer, medicine);
        userProcessContainer.add("ViewReportJPanel", vrjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Approve;
    private javax.swing.JTable ApproveTable;
    private javax.swing.JButton Decline;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
