/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.PatientRole;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatienttoPatientWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Krunal Nisar
 */
public class BlogsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BlogsJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount; 
    PatientOrganization organization;
    Enterprise enterprise;
    Network network;
    public BlogsJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise,Network network) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = (PatientOrganization) organization;
        this.enterprise= enterprise;
        this.network=network;
        populatePerson();
        chatBox();
        
    }

    public void populatePerson()
    {
        SelectPerson.removeAllItems();
        for(UserAccount ua : organization.getUserAccountDir().getUserAccountList())
        {
            SelectPerson.addItem(ua);
        }
    }
    public void chatBox()
    {
        int size=0;
        for(WorkRequest wr : userAccount.getWorkQueue().getWorkRequestList())
        {
            if(wr instanceof PatienttoPatientWorkRequest)
            {
               size++;
            }
        }
       // int size = userAccount.getWorkQueue().getWorkRequestList().size();
        int count =0;
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList())
        {
            if(request instanceof PatienttoPatientWorkRequest)
            {
                
                if(count == size -1)
                    {
                         String message = request.getMessage();
                         CharArea.append(message);
                         if(((PatienttoPatientWorkRequest)request).getTestResult() != null)
                      CharArea.append("\n" +((PatienttoPatientWorkRequest)request).getTestResult()) ;
                      

                    }
                    else
                    {
                        count++;
                    }
                
                
            
            }
        }
    }
    
    public void replyBox(String message)
    {
        int size = userAccount.getWorkQueue().getWorkRequestList().size();
        int count =0;
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList())
        {
            
            if(request instanceof PatienttoPatientWorkRequest)
            {
                //if(count == size -1)
                    //{
                        //if(request.getSender() != userAccount)
            {
                        ((PatienttoPatientWorkRequest)request).setTestResult(message);
                      CharArea.append("\n" +((PatienttoPatientWorkRequest)request).getTestResult()) ;
                      break;
                      
            }
                    //}
                   // else
                   // {
                    //    count++;
                    //}
                
                
            
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CharArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        Message = new javax.swing.JTextField();
        SelectPerson = new javax.swing.JComboBox();
        Replybutton = new javax.swing.JButton();
        Replytf = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();

        CharArea.setColumns(20);
        CharArea.setRows(5);
        jScrollPane1.setViewportView(CharArea);

        jButton1.setText("send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        SelectPerson.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SelectPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectPersonActionPerformed(evt);
            }
        });

        Replybutton.setText("Reply");
        Replybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReplybuttonActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Message)
                            .addComponent(Replytf, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Replybutton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(60, 60, 60)
                                .addComponent(SelectPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(337, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Message, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Replybutton)
                    .addComponent(Replytf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        UserAccount ua = (UserAccount) SelectPerson.getSelectedItem();
        
        String message = Message.getText();
        PatienttoPatientWorkRequest request = new PatienttoPatientWorkRequest();
        request.setMessage(message);
        ua.getWorkQueue().getWorkRequestList().add(request);
        userAccount.getWorkQueue().getWorkRequestList().add(request);
        chatBox();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SelectPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectPersonActionPerformed

    private void ReplybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReplybuttonActionPerformed
        // TODO add your handling code here:
       // String reply  = CharArea.getText();
        String message = Replytf.getText();
        replyBox(message);
        //reply = reply + "\n" + ReplyTF.getText();
        
    }//GEN-LAST:event_ReplybuttonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CharArea;
    private javax.swing.JTextField Message;
    private javax.swing.JButton Replybutton;
    private javax.swing.JTextField Replytf;
    private javax.swing.JComboBox SelectPerson;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
